name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload static files
        id: upload
        if: always()                       # ✅ This line ensures upload runs
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./                         # Or ./age-calculator if your files are inside that folder

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
